### ISSUE TITLE
NAND commands?

### ISSUE THREAD

**Issue by ParzivalWolfram** [linux-3ds/arm9linuxfw#22]
What would be required to get to the point of being able to issue raw NAND commands? It may be useful to get things like NAND backup/restore, fixing bricked devices, and the like to be supported at some point, at least in limited capacity?

**Comment by Wolfvak** [comment]
Well it's pretty much impossible to issue _raw_ commands through arm9linuxfw since it's only exposed as a block device, and those dont support raw CMDs. If you want a "dumb" backup/restore, it should be easy to add R/W support

Either way, arm9linuxfw is pretty much dead and the new sdhc driver on the linux side should be able to issue these commands.
